### ISSUE TITLE
ofx 9.4 <audiodecoder.h> not found , Mac OSX 10.12 

### ISSUE THREAD

**Issue by greena1re** [kylemcdonald/ofxAudioDecoder#6]
in ofxAudioDecoder.h for some reason the line: 

"#include `<audiodecoder.h>` isn't able to find the file.    I've tried hardcoding in the path and a bunch of other things but I can't figure out how to get it to recognize the file. 

Any ideas ?

**Comment by ofZach** [comment]
I think lib folder needs to be "libs" for the project generator to add it correctly to the project.
